name: 'Synchronize changes from cloud'
description: 'Synchronize changes from cloud'
inputs:
  cloud-repository-url:
    description: 'Url of the cloud repository to sync'
    required: true
  from-dir:
    description: 'Path to the current repository directory'
    required: true
  to-dir:
    description: 'Path to the sync repository directory'
    required: true
  token:
    description: 'Remove Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install kudusync
      run: npm install -g kudusync
      shell: powershell
    - name: Clone cloud repo
      run: git clone ${{ inputs.cloud-repository-url}} ${{ inputs.from-dir }}
      shell: powershell
    - name: Rempve GitHub PAT fromo nuget.config
      run: (Get-Content -path .\NuGet.config -Raw) -replace '${{ inputs.token }}','{PAT}' | Set-Content -Path .\NuGet.config
      shell: powershell
    - name: Kudusync
      run: kudusync --fromDir ${{ inputs.from-dir }} --toDir ${{ inputs.to-dir }} --ignore ".git" --nextManifest ../kudusyncmanifest.txt --ignoreManifest
      shell: powershell
    - name: Commit and push to Cloud
      run: |
            cd ${{ inputs.to-dir }}
            C:\.\DeploymentScripts\CommitAndPushToCloud.ps1 "${{github.run_number}}"
      shell: powershell
