name: 'Synchronize changes from cloud'
description: 'Synchronize changes from cloud'
inputs:
  cloud-repository-url:
    description: 'Url of the cloud repository to sync'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install kudusync
      run: npm install -g kudusync
      shell: powershell
    - name: Clone cloud repo
      run: git clone ${{ inputs.cloud-repository-url}} ..\cloud-repository
      shell: powershell
    - name: Kudusync
      run: kudusync --fromDir ..\cloud-repository --toDir .\*.web --ignore ".git" --nextManifest ../kudusyncmanifest.txt --ignoreManifest
      shell: powershell
    - name: Commit and push
      run: C:\.\DeploymentScripts\CommitAndPushToCloud.ps1 "${{github.run_number}}"
      shell: powershell